### PR TITLE
Unit ID explicit setting

### PR DESCRIPTION
**Pull request by chespinoza**
Proposal for an explicit Unit ID setting in the lib.
Tests Passed.

### CODE REVIEW

**Comment by hirschenberger** [comment]
Thanks for your PR. The implementation is totally ok, but I don't like having the UID as an extra parameter in all constructors (unfortunately rust has no default parameters). I think most of the time the UID is not necessary or defaults to 1.
But I also don't like to add another constructor with addr+uid and one with addr+port+uid.

So perhaps we should switch to the builder pattern for `Transport` construction [link](https://aturon.github.io/ownership/builders.html) and bump the version to `5.0`.

**Comment by flosse** [comment]
Another way would be using a config struct. In my [json-file-store](https://github.com/flosse/rust-json-file-store) I use `Store::new("foo")` and `Store::new_with_cfg("foo",cfg)` where `cfg` holds any kind of custom settings.

**Comment by chespinoza** [comment]
Ok, I think that @hirschenberger is right, I will dive into it more deeply to see if is possible get a better way to implement this.
 
Thanks for your feedback guys.

**Comment by hirschenberger** [comment]
I like @flosse 's proposal. @chespinoza I'd really appreciate a PR with an implementation in with his' proposal

**Comment by flosse** [comment]
BTW: adding a `tcp_timeout` field (for the [tcp stream](https://github.com/hirschenberger/modbus-rs/blob/master/src/tcp.rs#L55)) within the config would be cool :)

**Pull request closed without merging**
